language: python
python:
  - "2.6"
  - "2.7"
# python3 version not supported yet
#  - "3.2"
#  - "3.3"
# command to install dependencies
install: true
# command to run tests
script: nosetests --nocapture test
